import { BacklinksData, BacklinksFilterParams } from './backlinksTypes';

const DISAVOW_STORAGE_KEY = 'seo_studio_disavow_rules_v1';

export class BacklinksService {
  /**
   * Retrieves persistent disavowed items from local storage
   */
  static getDisavowedList(): string[] {
    try {
      const stored = localStorage.getItem(DISAVOW_STORAGE_KEY);
      if (stored) {
        return JSON.parse(stored);
      }
    } catch (e) {
      console.warn('Failed to read disavow list from localStorage', e);
    }
    // Default initial seeded disavowed items for demo
    return ['domain:free-seo-backlink-farm-99.xyz'];
  }

  /**
   * Adds domain or URL to disavow list
   */
  static addDisavowTarget(target: string): string[] {
    const current = this.getDisavowedList();
    const formatted = target.trim().toLowerCase();
    if (!current.includes(formatted)) {
      const updated = [...current, formatted];
      try {
        localStorage.setItem(DISAVOW_STORAGE_KEY, JSON.stringify(updated));
      } catch (e) {
        console.warn('Failed to save disavow list to localStorage', e);
      }
      return updated;
    }
    return current;
  }

  /**
   * Removes target from disavow list
   */
  static removeDisavowTarget(target: string): string[] {
    const current = this.getDisavowedList();
    const formatted = target.trim().toLowerCase();
    const updated = current.filter(item => item !== formatted);
    try {
      localStorage.setItem(DISAVOW_STORAGE_KEY, JSON.stringify(updated));
    } catch (e) {
      console.warn('Failed to save disavow list to localStorage', e);
    }
    return updated;
  }

  /**
   * Fetches backlinks data from server API
   */
  static async fetchBacklinks(params: BacklinksFilterParams): Promise<BacklinksData> {
    const disavowList = this.getDisavowedList();
    try {
      const response = await fetch('/api/backlinks', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          domain: params.domain,
          filter: params.filter,
          minDr: params.minDr,
          linkType: params.linkType,
          search: params.search,
          sortBy: params.sortBy,
          sortDir: params.sortDir,
          disavowList
        })
      });

      if (!response.ok) {
        throw new Error(`Server returned HTTP ${response.status}`);
      }

      const json = await response.json();
      if (!json.ok) {
        throw new Error(json.error || 'Failed to retrieve backlinks');
      }

      return json.data as BacklinksData;
    } catch (err: any) {
      console.error('Error fetching backlinks API:', err);
      throw err;
    }
  }

  /**
   * Generates official Google-compliant Disavow text file format
   */
  static generateGoogleDisavowContent(domain: string, disavowList: string[]): string {
    const timestamp = new Date().toISOString().split('T')[0];
    const header = [
      `# Google Search Console Disavow Links File`,
      `# Target Domain: ${domain}`,
      `# Generated by SEO Studio Pro (Phase 18 Backlinks Engine)`,
      `# Date Generated: ${timestamp}`,
      `# Total Disavowed Rules: ${disavowList.length}`,
      `# Documentation: https://support.google.com/webmasters/answer/2648487`,
      ``
    ];

    const rules = disavowList.map(rule => {
      const clean = rule.trim();
      if (clean.startsWith('http://') || clean.startsWith('https://')) {
        return clean;
      }
      if (clean.startsWith('domain:')) {
        return clean;
      }
      return `domain:${clean}`;
    });

    return [...header, ...rules, ``].join('\n');
  }

  /**
   * Triggers browser download for disavow.txt
   */
  static downloadDisavowFile(domain: string, disavowList: string[]): void {
    const content = this.generateGoogleDisavowContent(domain, disavowList);
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `disavow_${domain.replace(/[^a-zA-Z0-9]/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
